README.rst

This adds the usual badges to the README

DOC: add README badges

---

setup.cfg

Publishing the package fails due to a wrong author email address: https://github.com/audeering/audonnx/runs/4758570898?check_suite_focus=true

Fix author email address in package metadata

---

.github/workflows/publish.yml

There was still an error when building the docs for publication: https://github.com/audeering/audonnx/runs/4758827388?check_suite_focus=true as the dependencies were not installed.

CI: fix installing of publish doc dependencies

---

audonnx/core/api.py
audonnx/core/model.py
docs/requirements.txt
docs/usage.rst
tests/test_load.py
tests/test_model.py

Since ORT 1.9 it is required to explicitly set the providers parameter when instantiating InferenceSession.
This adds the argument `device_or_providers`, which can be set to a device (e.g. `cuda:2`) or a list of [providers](https://onnxruntime.ai/docs/execution-providers/).

Argument to set device or providers

---

setup.cfg
tests/requirements.txt

With the introduction of `device` in #8, we now require  `onnxruntime>=1.1.0` for the package and  `onnxruntime>=1.8.0` for the tests.

Update dependency to onnxruntime

---

audonnx/core/model.py

To avoid a package dependency to `audiofile` we import it only in the docstring.

DOC: import audiofile in docstring

---

audonnx/core/model.py
tests/conftest.py
tests/test_model.py

Closes #17 
In ONNX format axis with a dynamic size are represented by a string. This is not convenient as we cannot directly use it to e.g. reshape an input array to match the expected shape. We therefore replace the string with -1 in the node classes of `audonnx`.

Input/output node shape: replace dynamic axis with -1

---

audonnx/core/model.py
audonnx/core/node.py
docs/requirements.txt
tests/test_model.py

Closes #20 
Labels are now assigned to the last non-dynamic dimension. The docstring has been adapted and is also more precise now:
Example from #20 now works as expected:
```python
class TorchModel(torch.nn.Module):
def __init__(
self,
):
super().__init__()
def forward(self, x: torch.Tensor):
return torch.cat([x, x])
torch_model = TorchModel()
input = torch.randn((1, 10))  # batch, time, feature
output = torch_model(input)
print(output)
onnx_path = 'model.onnx'
torch.onnx.export(
torch_model,
input,
onnx_path,
input_names=['input'],
output_names=['output'],
dynamic_axes={
'input': {1: 'time'},
'output': {1: 'time'},
},
opset_version=12,
)
audonnx.Model(
onnx_path,
labels=['left', 'right'],
)
```
```
Input:
input:
shape: [1, -1]
dtype: tensor(float)
transform: None
Output:
output:
shape: …
```

Support output nodes where last dimension is dynamic

---

audonnx/core/model.py
audonnx/core/testing.py
tests/test_model.py

Adds option to Initialize `Model` from ONNX object and removes `root` argument from `testing.create_model()`.

Init model from ONNX object

---

audonnx/core/api.py
audonnx/core/model.py
tests/conftest.py

As we have already
```
audobject >=0.7.1
```
in the requirements and `audobject >=0.7.1` depends on `audeer >=1.18.0` it's safe to simply switch to `audeer.path()`.

Use audeer.path() instead of audeer.safe_path()

---

audonnx/core/model.py
audonnx/core/testing.py
audonnx/core/typing.py
audonnx/testing/__init__.py
docs/api-testing.rst
setup.cfg
tests/conftest.py
tests/requirements.txt
tests/test_install.py
tests/test_load.py
tests/test_model.py
tests/test_node.py

All test are now based on `audonnx.testing`.
To make it easier writing the tests I added `testing.create_model_proto()` to the API:

TST: refactor using audonnx.testing

---

audonnx/core/model.py
docs/usage.rst
tests/test_model.py

Closes #26 
```python
import audonnx.testing
sampling_rate = 16000
signal = np.zeros((1, 10), np.float32)
shapes = [[1, 2], [3, -1]]
model = audonnx.testing.create_model(shapes)
model(signal, sampling_rate, output_names='output-0')
```
```
UserWarning: 'output_names' argument is deprecated and will be removed with version 1.2.0. Use 'outputs' instead.
y = model(signal, sampling_rate, output_names='output-0')
[[0. 0.]]
```

Rename argument output_names to outputs

---

audonnx/core/model.py
docs/usage.rst
tests/test_model.py

Adds new keyword argument `concat` to `Model__call__()`. If set to `True` the output of the requested nodes will be concatenated:
```python
import audonnx.testing
sampling_rate = 16000
signal = np.zeros((1, 10), np.float32)
shapes = [[1, 3], [1, 2]]
model = audonnx.testing.create_model(shapes)
model(signal, sampling_rate)
```
```
{'output-0': array([[0., 0., 0.]], dtype=float32), 'output-1': array([[0., 0.]], dtype=float32)}
```
```python
model(signal, sampling_rate, concat=True)
```
```
[[0. 0. 0. 0. 0.]]
```

Add option to concatenate outputs

---

.github/workflows/test.yml
tests/test_install.py

Closes #2 
This enables tests under Windows.
Only one test for `auto_install` is skipped as deinstalling `opensmile` under Windows does not work as we don't have the permission to remove the included DLL file when this is still loaded.

TST: enable Windows tests

---

docs/requirements.txt
setup.cfg

Closes #40 
Adds `onnx >=1.8.0` to `install_requires` in `setup.cfg`.

Add missing onnx to requirements

---

setup.cfg

Update to `audobject>=0.7.2` to avoid bug with `audinterface>=0.9.0`, see https://github.com/audeering/audinterface/issues/68

Require audobject>=0.7.2

---

.github/workflows/test.yml
.pre-commit-config.yaml
CONTRIBUTING.rst
audonnx/core/api.py
audonnx/core/testing.py
docs/requirements.txt
setup.cfg
tests/conftest.py
tests/requirements.txt
tests/test_install.py

Alternative to https://github.com/audeering/audonnx/pull/47
This uses [pre-commit](https://pre-commit.com) instead of `pytest` to execute the `flake8` tests.
It also fixes a few flake8 issues and adds a coding convention section to CONTRIBUTING.

TST: use pre-commit for flake8 checks

---

.github/workflows/publish.yml

The new plugin uses `name` instead of `release_name` to specify the name of the release.

CI: fix name of release

---

.github/workflows/test.yml
audonnx/core/testing.py
docs/requirements.txt

Closes https://github.com/audeering/audonnx/issues/48
Newer versions of `onnx` and `protobuf` are now compatible and we can use them (we also have to use them to be compatible with newer `onnxruntime` versions).

DOC: do not restrict onnx and protobuf versions

---

.github/workflows/test.yml
docs/usage.rst

Closes #67
This adds a pre-processing step before the quantization of the model as proposed at https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/image_classification/cpu/ReadMe.md#pre-processing.
When not adding this stage, the quantization will raise a warning message that we should apply pre-processing.
This was also the reason the `-W` flag was deactivated when building the docs, which I revert in this pull request.
The page linked above states:
> The pre-processing consists of the following optional steps
>
> * Symbolic Shape Inference. It works best with transformer models.
> * ONNX Runtime Model Optimization.
> * ONNX Shape Inference.
>
> Quantization requires tensor shape information to perform its best. Model optimization also improve the …

DOC: add pre-processing stage for quantization

---

audonnx/__init__.py

`pkg_resources` is deprecated and since Python 3.8 we can use `importlib.metadata` to get the version of a package.

Use importlib.metadata instead of pkg_resources

---

.github/workflows/publish.yml

Following the code example from https://github.com/actions/deploy-pages this tries to fix write permissions to publish to Github pages.

CI: fix permissions to publish Github pages

---

audonnx/__init__.py
audonnx/core/model.py
audonnx/core/ort.py
docs/api-src/audonnx.rst

Closes #76 
This adds `audonnx.device_to_providers()` to the public API.

Add audonnx.device_to_providers()

---

audonnx/core/api.py
audonnx/core/model.py
audonnx/core/testing.py
tests/test_model.py

Closes #80 
This adds the `num_workers` argument to `audonnx.Model` and `audonnx.load()`. It now only uses 1 thread by default, whereas before onnxruntime chose the number by default.
The `num_workers` argument was also added to `audonnx.testing.create_model()`.

Add num_workers to audonnx.Model and load()

---

audonnx/core/api.py
audonnx/core/model.py
audonnx/core/testing.py
docs/conf.py
tests/test_model.py

Closes #82 
This adds the argument `session_options` to `audonnx.Model` and `audonnx.load()`. The `session_options` argument takes precedence over the `num_workers` argument. This means that if `session_options` is not `None`, you don't have to worry about also setting `num_workers` to the intended value. And if you choose to set `num_workers` instead, `session_options` defaults to `None` and doesn't need to be adjusted either.
Additionally, the `session_options` argument is added to `audonnx.testing.create_model()`, and the link(s) for `provider(s)` in the docstring of `audonnx.Model`, `audonnx.load()`, and `audonnx.testing.create_model()` were fixed/adjusted.

Add session_options to audonnx.Model and load()

---

CHANGELOG.rst

Add missing Python 3.11 support to changelog for version 0.6.4.

DOC: add missing changelog entry

---

pyproject.toml

Require `onnxruntime>=1.12.0` so we can drop support for Python 3.9 in a next step.

Depend on onnxruntime>=1.12.0
